version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    privileged: true
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - postgres-data:/var/lib/postgresql/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgresql.entrypoints=postgresql"
      - "traefik.tcp.routers.postgresql.rule=HostSNI(`*`)"
      - "traefik.tcp.services.postgresql.loadbalancer.server.port=5432"
  postgres-replica:
    container_name: postgres-replica
    image: postgres:latest
    privileged: true
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
    volumes:
      - postgres-replica-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/DockerVolumes/postgresql/postgres/data
  postgres-replica-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/DockerVolumes/postgresql/postgres-replica/data

networks:
  default:
    external:
      name: network-dev
